services:
  server:
    container_name: server
    build: flasky/Dockerfile
    image: server
    # command: flask --app flasky run --host 0.0.0.0 --debug
    networks:
      - cool

  client:
    container_name: client
    build: flasky_client/Dockerfile
    image: client
    command: check server
    networks:
      - cool

networks:
  cool:
    name: cool
    external: true
